Add shardsWhitelist to template.
4teamwork/ftw.recipe.solr pull request #12
Opened 2020-05-15 13:21 UTC by lvonlanthen

Allow providing a `shardsWhitelist` option being passed to the `ShardHandlerFactory`. This allows to limits what nodes can be requested in the shards request parameter (see https://lucene.apache.org/solr/guide/8_1/distributed-requests.html#configuring-the-shardhandlerfactory)

Example `buildout.cfg` (e.g. in https://github.com/4teamwork/ris-solr/):

```
[buildout]
extends = base.cfg

[solr]
port = 12830
shards-whitelist = localhost:12830/solr/ris,localhost:10630/solr/kr
```

2020-05-15 14:20 UTC, bierik approved these changes
LGTM

2020-05-15 14:38 UTC, buchi requested changes
Tests are missing. Otherwise looks good.

2020-05-15 19:47 UTC, lvonlanthen commented
@buchi Updated, a test is now included.

2020-05-18 16:06 UTC, buchi approved these changes

2020-05-19 11:14 UTC, merged